prisma-router:
  ports:
  - 80:8080
  tty: true
  image: rancher/load-balancer-service
  links:
  - hhhtomcat-9-jre8:hhhtomcat-9-jre8
  stdin_open: true
hhhtomcat-9-jre8:
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
  tty: true
  image: tomcat:9.0.0-jre8
  stdin_open: true

